"""0002_добавил_поле_filename_у_фотографий_профиля

Revision ID: b4056dda0936
Revises: d53be3a35511
Create Date: 2025-05-05 21:06:32.080386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4056dda0936'
down_revision: Union[str, None] = 'd53be3a35511'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_photos', sa.Column('filename', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile_photos', 'filename')
    # ### end Alembic commands ###
