"""0003_добавил_поле_название_для_проектов_в_таблицу

Revision ID: be10a7640a29
Revises: b4056dda0936
Create Date: 2025-05-31 10:50:44.163131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be10a7640a29'
down_revision: Union[str, None] = 'b4056dda0936'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('title', sa.VARCHAR(length=150), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'title')
    # ### end Alembic commands ###
