"""0004_добавил_поле_filename_в_таблицу_profect_files

Revision ID: e53896c51cf8
Revises: be10a7640a29
Create Date: 2025-05-31 11:14:31.502960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e53896c51cf8'
down_revision: Union[str, None] = 'be10a7640a29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_files', sa.Column('filename', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_files', 'filename')
    # ### end Alembic commands ###
